version: "3.7"
services:
  devourer:
    image: devourer
    networks:
      - mainnet
      - tikanet
    depends_on:
      - tika
    ports:
      - "9009:80"
    environment:
      - TIKA_SERVER_ENDPOINT="tika:9998"
      - AUDIO_DUMP_DIR="/tmp"
      - WIKI_SEARCH_URL="https://en.wikipedia.org/w/api.php"
      - SERVER_DEPLOYMENT_TYPE=deployment
    cap_drop:
      - ALL
    entrypoint: ["/docker-entrypoint.sh"]
  tika:
    image: apache/tike:2.0.0
    networks:
      - tikanet
    cap_drop:
      - ALL
networks:
  mainnet:
  tikanet:
