version: "3.7"
services:
  devourer:
    image: devourer
    build:
      context: ./devourer
    networks:
      - mainnet
      - tikanet
    depends_on:
      - tika
      - cargo
    ports:
      - "19019:80"
    environment:
      - TIKA_SERVER_ENDPOINT=http://tika:9998
      - AUDIO_DUMP_DIR=/tmp
      - WIKI_SEARCH_URL=https://en.wikipedia.org/w/api.php
      - SERVER_DEPLOYMENT_TYPE=test
      - TIKA_CLIENT_ONLY=True
    cap_drop:
      - ALL
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - devourer-nltk-data:/root/nltk_data/
  tika:
    image: apache/tika:2.0.0
    networks:
      - tikanet
    cap_drop:
      - ALL
  cargo:
    image: devourer-cargo
    build:
      context: ./devourer
    networks:
      - mainnet
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_VAULT=/cargo-vault
    volumes:
      - cargo-vault:/cargo-vault
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    entrypoint: ["/cargo/cargo.py"]
networks:
  mainnet:
  tikanet:
volumes:
  cargo-vault:
  devourer-nltk-data:
